---
- name: Pull docker image of Calculator
  hosts: localhost
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull kayrohit/scientific_calc

    - name: remove existing previous version of the container
      shell: docker stop cal && docker rm cal

    - name: remove previous image with none tag
      shell: docker rmi $(docker images | grep "none" | awk '{print $3}')

    - name: running container
#      shell: docker create -it --name calculator kayrohit/scientific_calc /bin/bash
      shell: docker run -it --name cal -d kayrohit/scientific_calc